// ZAG sites, generated from build.py. Edit here to change the map.
window.ZAG = {
 "sectors": {
  "bridge": {
   "name": "Bridges and viaducts",
   "colour": "#1273D4"
  },
  "ai": {
   "name": "AI, data and monitoring",
   "colour": "#7B4BD8"
  },
  "build": {
   "name": "Buildings and structures",
   "colour": "#C77A0E"
  },
  "mat": {
   "name": "Materials and circularity",
   "colour": "#1E9A57"
  },
  "fire": {
   "name": "Fire safety",
   "colour": "#D9453A"
  },
  "geo": {
   "name": "Geotechnics and ground",
   "colour": "#96602A"
  },
  "energy": {
   "name": "Hydropower and energy",
   "colour": "#0E93A6"
  },
  "herit": {
   "name": "Cultural heritage",
   "colour": "#C0398C"
  },
  "inst": {
   "name": "Institutions and laboratories",
   "colour": "#60687A"
  },
  "tunnel": {
   "name": "Tunnels and underground",
   "colour": "#5A4FCF"
  },
  "cable": {
   "name": "Cableways and lifts",
   "colour": "#0E8F8F"
  },
  "quake": {
   "name": "Earthquake response",
   "colour": "#B8532A"
  }
 },
 "sites": [
  {
   "id": "tomacevo",
   "name": "Tomačevo Bridge",
   "name_sl": "Most čez Savo v Tomačevem",
   "evidence": "doc",
   "lat": 46.0856,
   "lon": 14.53642,
   "precision": "derived",
   "location": "Ljubljana",
   "sector": "ai",
   "role": "Bridge weigh-in-motion and structural health monitoring",
   "years": "2023–2025",
   "client": "",
   "region": "SI041",
   "built": "1982"
  },
  {
   "id": "ravbarkomanda",
   "name": "Ravbarkomanda Viaduct",
   "name_sl": "Viadukt Ravbarkomanda",
   "evidence": "doc",
   "lat": 45.821,
   "lon": 14.24,
   "precision": "approximate",
   "location": "A1 between Planina and Postojna",
   "sector": "ai",
   "role": "Long-term structural health monitoring and bridge weigh-in-motion",
   "years": "2023–2024",
   "client": "DARS",
   "region": "SI038",
   "built": "1972"
  },
  {
   "id": "vransko",
   "name": "Vransko Bridge",
   "name_sl": "Most pri Vranskem",
   "evidence": "doc",
   "lat": 46.25111,
   "lon": 14.94472,
   "precision": "locality",
   "location": "Vransko",
   "sector": "ai",
   "role": "Bridge weigh-in-motion and direct measurement of dynamic amplification",
   "years": "2006–2009",
   "client": "",
   "region": "SI034",
   "built": ""
  },
  {
   "id": "nm_brv",
   "name": "Novo Mesto Stress Ribbon Footbridge",
   "name_sl": "Brv čez Krko, Novo mesto",
   "evidence": "doc",
   "lat": 45.801095,
   "lon": 15.152007,
   "precision": "surveyed",
   "location": "Novo mesto",
   "sector": "bridge",
   "role": "Static and dynamic load testing, and validation of the finite element model",
   "years": "2023",
   "client": "Mestna občina Novo mesto",
   "region": "SI037",
   "built": "2023"
  },
  {
   "id": "crna",
   "name": "Črna na Koroškem Bridge",
   "name_sl": "Most v Črni na Koroškem",
   "evidence": "doc",
   "lat": 46.4697417,
   "lon": 14.8489639,
   "precision": "locality",
   "location": "Črna na Koroškem",
   "sector": "mat",
   "role": "Structural reuse of salvaged precast girders",
   "years": "2023–2024",
   "client": "Direkcija RS za infrastrukturo",
   "region": "SI033",
   "built": "2024"
  },
  {
   "id": "verd",
   "name": "Verd Viaduct",
   "name_sl": "Viadukt Verd",
   "evidence": "doc",
   "lat": 45.95555,
   "lon": 14.30524,
   "precision": "surveyed",
   "location": "Verd, Vrhnika",
   "sector": "mat",
   "role": "First Slovenian application of an expansive grout additive",
   "years": "",
   "client": "DARS",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "he_solkan",
   "name": "HE Solkan",
   "name_sl": "Hidroelektrarna Solkan",
   "evidence": "doc",
   "lat": 45.9694972,
   "lon": 13.6454917,
   "precision": "locality",
   "location": "Solkan, Nova Gorica",
   "sector": "energy",
   "role": "Expansive and non-shrink cement grouts",
   "years": "",
   "client": "Soške elektrarne Nova Gorica",
   "region": "SI043",
   "built": "1984"
  },
  {
   "id": "he_zlatolicje",
   "name": "HE Zlatoličje",
   "name_sl": "Hidroelektrarna Zlatoličje",
   "evidence": "doc",
   "lat": 46.4479,
   "lon": 15.7868,
   "precision": "surveyed",
   "location": "Zlatoličje, Starše",
   "sector": "energy",
   "role": "Expansive and non-shrink cement grouts; third party quality control of the upgrade",
   "years": "2006–2009",
   "client": "Dravske elektrarne Maribor",
   "region": "SI032",
   "built": "1969"
  },
  {
   "id": "he_vuhred",
   "name": "HE Vuhred",
   "name_sl": "Hidroelektrarna Vuhred",
   "evidence": "doc",
   "lat": 46.5876,
   "lon": 15.2756,
   "precision": "surveyed",
   "location": "Vuhred, Radlje ob Dravi",
   "sector": "energy",
   "role": "Expansive and non-shrink cement grouts",
   "years": "",
   "client": "Dravske elektrarne Maribor",
   "region": "SI033",
   "built": "1956"
  },
  {
   "id": "strunjan",
   "name": "Sveti Križ Bay Cliff",
   "name_sl": "Zaliv Sv. Križa v Strunjanu",
   "evidence": "doc",
   "lat": 45.537465,
   "lon": 13.610151,
   "precision": "surveyed",
   "location": "Strunjan, Piran",
   "sector": "geo",
   "role": "Rockfall investigation and slope characterisation",
   "years": "2019–2021",
   "client": "",
   "region": "SI044",
   "built": ""
  },
  {
   "id": "sitarjevec",
   "name": "Sitarjevec Mine",
   "name_sl": "Rudnik Sitarjevec v Litiji",
   "evidence": "doc",
   "lat": 46.049342,
   "lon": 14.830746,
   "precision": "address",
   "location": "Litija",
   "sector": "geo",
   "role": "Characterisation of mine ochre as a pigment",
   "years": "2021",
   "client": "",
   "region": "SI035",
   "built": ""
  },
  {
   "id": "zag",
   "name": "ZAG",
   "name_sl": "Zavod za gradbeništvo Slovenije",
   "evidence": "inst",
   "lat": 46.0657,
   "lon": 14.5128,
   "precision": "address",
   "location": "Dimičeva ulica 12, Ljubljana",
   "sector": "inst",
   "role": "Slovenian National Building and Civil Engineering Institute",
   "years": "founded 1949",
   "client": "",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "zag_logatec",
   "name": "ZAG Fire Laboratory Logatec",
   "name_sl": "Požarni laboratorij ZAG Logatec",
   "evidence": "inst",
   "lat": 45.91795,
   "lon": 14.24163,
   "precision": "address",
   "location": "Obrtna cona 35, Logatec",
   "sector": "fire",
   "role": "Fire resistance and reaction to fire testing",
   "years": "2022 onwards",
   "client": "",
   "region": "SI041",
   "built": "2022"
  },
  {
   "id": "zag_gameljne",
   "name": "ZAG Fire Laboratory Gameljne",
   "name_sl": "Požarni laboratorij ZAG Gameljne",
   "evidence": "inst",
   "lat": 46.1216,
   "lon": 14.4907,
   "precision": "locality",
   "location": "Zgornje Gameljne, Ljubljana",
   "sector": "fire",
   "role": "Original ZAG fire testing facility, until Logatec opened",
   "years": "1986 onwards",
   "client": "",
   "region": "SI041",
   "built": "1986"
  },
  {
   "id": "zag_maribor",
   "name": "ZAG Maribor Unit",
   "name_sl": "ZAG enota Maribor, Dobrovce",
   "evidence": "inst",
   "lat": 46.48223,
   "lon": 15.70206,
   "precision": "address",
   "location": "Dobrovce, Miklavž na Dravskem polju",
   "sector": "inst",
   "role": "ZAG regional unit for north-east Slovenia",
   "years": "2021 onwards",
   "client": "",
   "region": "SI032",
   "built": "2021"
  },
  {
   "id": "cestel",
   "name": "Cestel d.o.o.",
   "name_sl": "Cestel cestni inženiring d.o.o.",
   "evidence": "inst",
   "lat": 46.11727,
   "lon": 14.54599,
   "precision": "address",
   "location": "Spruha 32, Trzin",
   "sector": "ai",
   "role": "Industrial partner on bridge weigh-in-motion work, maker of SiWIM",
   "years": "",
   "client": "",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "innorenew",
   "name": "InnoRenew CoE",
   "name_sl": "InnoRenew CoE, Izola",
   "evidence": "inst",
   "lat": 45.53022,
   "lon": 13.64899,
   "precision": "address",
   "location": "Livade 6a, Izola",
   "sector": "inst",
   "role": "Partner institute, ZAG is a founding partner",
   "years": "2017–2022",
   "client": "",
   "region": "SI044",
   "built": "2017"
  },
  {
   "id": "ulfgg",
   "name": "UL FGG",
   "name_sl": "Fakulteta za gradbeništvo in geodezijo",
   "evidence": "inst",
   "lat": 46.0455,
   "lon": 14.4945,
   "precision": "address",
   "location": "Jamova cesta 2, Ljubljana",
   "sector": "inst",
   "role": "Faculty of Civil and Geodetic Engineering, nearest academic partner",
   "years": "",
   "client": "",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "karavanke_c",
   "name": "Karavanke Motorway Tunnel",
   "name_sl": "Predor Karavanke, avtocesta",
   "evidence": "doc",
   "lat": 46.45371,
   "lon": 13.99048,
   "precision": "surveyed",
   "location": "Hrušica, Jesenice",
   "sector": "tunnel",
   "role": "External control of the repair works, and geological-geotechnical investigations for the design",
   "years": "1990–2014",
   "client": "DARS",
   "region": "SI042",
   "built": ""
  },
  {
   "id": "karavanke_r",
   "name": "Karavanke Railway Tunnel",
   "name_sl": "Predor Karavanke, železnica",
   "evidence": "doc",
   "lat": 46.44924,
   "lon": 14.01555,
   "precision": "surveyed",
   "location": "Jesenice",
   "sector": "tunnel",
   "role": "External control of the repair works",
   "years": "1998–2014",
   "client": "DARS",
   "region": "SI042",
   "built": ""
  },
  {
   "id": "golovec",
   "name": "Golovec Tunnel",
   "name_sl": "Predor Golovec",
   "evidence": "doc",
   "lat": 46.01739,
   "lon": 14.55893,
   "precision": "surveyed",
   "location": "Ljubljana",
   "sector": "tunnel",
   "role": "External control of the quality of construction, and geological-geotechnical investigations for the design",
   "years": "1990–2014",
   "client": "DARS",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "sentvid",
   "name": "Šentvid Tunnel",
   "name_sl": "Predor Šentvid",
   "evidence": "doc",
   "lat": 46.08816,
   "lon": 14.46048,
   "precision": "surveyed",
   "location": "Ljubljana",
   "sector": "tunnel",
   "role": "External control of the quality of construction, and geological-geotechnical investigations for the design",
   "years": "1990–2014",
   "client": "DARS",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "trojane",
   "name": "Trojane Tunnel",
   "name_sl": "Predor Trojane",
   "evidence": "doc",
   "lat": 46.1836,
   "lon": 14.8604,
   "precision": "surveyed",
   "location": "Trojane, Lukovica",
   "sector": "tunnel",
   "role": "External control of the quality of construction, and geological-geotechnical investigations for the design",
   "years": "1990–2014",
   "client": "DARS",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "podmilj",
   "name": "Podmilj Tunnel",
   "name_sl": "Predor Podmilj",
   "evidence": "doc",
   "lat": 46.1761,
   "lon": 14.8433,
   "precision": "settlement",
   "location": "Podmilj, Lukovica",
   "sector": "tunnel",
   "role": "External control of the quality of construction",
   "years": "1998–2014",
   "client": "DARS",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "vzideh",
   "name": "V Zideh Tunnel",
   "name_sl": "Predor V Zideh",
   "evidence": "doc",
   "lat": 46.1884,
   "lon": 14.8933,
   "precision": "settlement",
   "location": "V Zideh, Lukovica",
   "sector": "tunnel",
   "role": "External control of the quality of construction",
   "years": "1998–2014",
   "client": "DARS",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "kastelec",
   "name": "Kastelec Tunnel",
   "name_sl": "Predor Kastelec",
   "evidence": "doc",
   "lat": 45.57724,
   "lon": 13.87372,
   "precision": "surveyed",
   "location": "Kastelec, Koper",
   "sector": "tunnel",
   "role": "External control of the quality of construction",
   "years": "1998–2014",
   "client": "DARS",
   "region": "SI044",
   "built": ""
  },
  {
   "id": "dekani",
   "name": "Dekani Tunnel",
   "name_sl": "Predor Dekani",
   "evidence": "doc",
   "lat": 45.55161,
   "lon": 13.8304,
   "precision": "surveyed",
   "location": "Dekani, Koper",
   "sector": "tunnel",
   "role": "External control of the quality of construction",
   "years": "1998–2014",
   "client": "DARS",
   "region": "SI044",
   "built": ""
  },
  {
   "id": "markovec",
   "name": "Markovec Tunnel",
   "name_sl": "Predor Markovec",
   "evidence": "doc",
   "lat": 45.54318,
   "lon": 13.71591,
   "precision": "surveyed",
   "location": "Koper",
   "sector": "tunnel",
   "role": "External control of the quality of construction",
   "years": "1998–2014",
   "client": "DARS",
   "region": "SI044",
   "built": ""
  },
  {
   "id": "lescevje",
   "name": "Leščevje Tunnel",
   "name_sl": "Predor Leščevje",
   "evidence": "doc",
   "lat": 45.9159,
   "lon": 14.7844,
   "precision": "settlement",
   "location": "Leščevje, Trebnje",
   "sector": "tunnel",
   "role": "External control of the quality of construction",
   "years": "1998–2014",
   "client": "DARS",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "cenkova",
   "name": "Cenkova Tunnel",
   "name_sl": "Predor Cenkova",
   "evidence": "doc",
   "lat": 46.5745,
   "lon": 15.9391,
   "precision": "settlement",
   "location": "Cenkova, Cerkvenjak",
   "sector": "tunnel",
   "role": "External control of the quality of construction",
   "years": "1998–2014",
   "client": "DARS",
   "region": "SI032",
   "built": ""
  },
  {
   "id": "pletovarje",
   "name": "Pletovarje Tunnel",
   "name_sl": "Predor Pletovarje",
   "evidence": "doc",
   "lat": 46.2839,
   "lon": 15.4327,
   "precision": "settlement",
   "location": "Pletovarje, Slovenske Konjice",
   "sector": "tunnel",
   "role": "Geological-geotechnical investigations for the design",
   "years": "1990–2013",
   "client": "DARS",
   "region": "SI034",
   "built": ""
  },
  {
   "id": "golo_rebro",
   "name": "Golo Rebro Tunnel",
   "name_sl": "Predor Golo Rebro",
   "evidence": "doc",
   "lat": 46.3137,
   "lon": 15.45759,
   "precision": "surveyed",
   "location": "Slovenske Konjice",
   "sector": "tunnel",
   "role": "Geological-geotechnical investigations for the design",
   "years": "1990–2013",
   "client": "DARS",
   "region": "SI034",
   "built": ""
  },
  {
   "id": "tabor_h4",
   "name": "Tabor Tunnel",
   "name_sl": "Predor Tabor",
   "evidence": "doc",
   "lat": 45.808,
   "lon": 13.9679,
   "precision": "settlement",
   "location": "Podnanos, Vipava",
   "sector": "tunnel",
   "role": "External control of the quality of construction, and geological-geotechnical investigations for the design",
   "years": "1990–2014",
   "client": "DARS",
   "region": "SI043",
   "built": ""
  },
  {
   "id": "he_vrhovo",
   "name": "HE Vrhovo",
   "name_sl": "Hidroelektrarna Vrhovo",
   "evidence": "doc",
   "lat": 46.0442,
   "lon": 15.2237,
   "precision": "surveyed",
   "location": "Vrhovo, Radeče",
   "sector": "energy",
   "role": "Numerical modelling of the dam structure",
   "years": "2012",
   "client": "Savske elektrarne Ljubljana, d.o.o.",
   "region": "SI036",
   "built": ""
  },
  {
   "id": "jez_melje",
   "name": "Melje Dam and Small HPP",
   "name_sl": "Jez Melje in MHE Melje",
   "evidence": "doc",
   "lat": 46.56247,
   "lon": 15.64398,
   "precision": "municipality",
   "location": "Melje, Maribor",
   "sector": "energy",
   "role": "Third party quality control of the materials used in the upgrade",
   "years": "2006–2009",
   "client": "Dravske elektrarne Maribor, d.o.o.",
   "region": "SI032",
   "built": ""
  },
  {
   "id": "he_bostanj",
   "name": "HE Boštanj",
   "name_sl": "Hidroelektrarna Boštanj",
   "evidence": "doc",
   "lat": 46.0171,
   "lon": 15.2812,
   "precision": "surveyed",
   "location": "Boštanj, Sevnica",
   "sector": "energy",
   "role": "Third party quality control of materials, and monitoring during and after construction",
   "years": "2007–2013",
   "client": "HESS, d.o.o. and INFRA, d.o.o.",
   "region": "SI036",
   "built": ""
  },
  {
   "id": "he_arto",
   "name": "HE Arto Blanca",
   "name_sl": "Hidroelektrarna Arto Blanca",
   "evidence": "doc",
   "lat": 45.9895,
   "lon": 15.3813,
   "precision": "surveyed",
   "location": "Blanca, Sevnica",
   "sector": "energy",
   "role": "Third party quality control of materials, and monitoring during and after construction",
   "years": "2007–2013",
   "client": "HESS, d.o.o. and INFRA, d.o.o.",
   "region": "SI036",
   "built": ""
  },
  {
   "id": "he_krsko",
   "name": "HE Krško",
   "name_sl": "Hidroelektrarna Krško",
   "evidence": "doc",
   "lat": 45.9748,
   "lon": 15.4815,
   "precision": "surveyed",
   "location": "Krško",
   "sector": "energy",
   "role": "Third party quality control of materials, and monitoring during and after construction",
   "years": "2007–2013",
   "client": "HESS, d.o.o. and INFRA, d.o.o.",
   "region": "SI036",
   "built": ""
  },
  {
   "id": "che_avce",
   "name": "CHE Avče",
   "name_sl": "Črpalna hidroelektrarna Avče",
   "evidence": "doc",
   "lat": 46.1027,
   "lon": 13.6707,
   "precision": "surveyed",
   "location": "Avče, Kanal ob Soči",
   "sector": "energy",
   "role": "Third party quality control of materials, and monitoring during and after construction",
   "years": "2007–2009",
   "client": "Soške elektrarne Nova Gorica, d.o.o.",
   "region": "SI043",
   "built": ""
  },
  {
   "id": "slano_blato",
   "name": "Slano Blato Landslide",
   "name_sl": "Plaz Slano blato",
   "evidence": "doc",
   "lat": 45.909,
   "lon": 13.87,
   "precision": "surveyed",
   "location": "Lokavec, Ajdovščina",
   "sector": "geo",
   "role": "Geological-geomechanical investigations for the landslide",
   "years": "2001–2004",
   "client": "Ministry of the Environment and Spatial Planning",
   "region": "SI043",
   "built": ""
  },
  {
   "id": "stoze",
   "name": "Stože Landslide",
   "name_sl": "Plaz Stože pod Mangartom",
   "evidence": "doc",
   "lat": 46.40591,
   "lon": 13.60312,
   "precision": "settlement",
   "location": "Log pod Mangartom, Bovec",
   "sector": "geo",
   "role": "Investigations of the shear properties of the landslide mass",
   "years": "2002",
   "client": "Ministry of Defence",
   "region": "SI043",
   "built": ""
  },
  {
   "id": "krvavec",
   "name": "Krvavec Cableway",
   "name_sl": "Žičnice Krvavec",
   "evidence": "doc",
   "lat": 46.28495,
   "lon": 14.49594,
   "precision": "surveyed",
   "location": "Grad, Cerklje na Gorenjskem",
   "sector": "cable",
   "role": "Periodical technical inspections of cableway installations",
   "years": "",
   "client": "RTC Krvavec, d.d.",
   "region": "SI042",
   "built": ""
  },
  {
   "id": "velikaplanina",
   "name": "Velika Planina Cableway",
   "name_sl": "Žičnica Velika planina",
   "evidence": "doc",
   "lat": 46.30553,
   "lon": 14.60863,
   "precision": "surveyed",
   "location": "Kamniška Bistrica, Kamnik",
   "sector": "cable",
   "role": "Periodical technical inspections of cableway installations",
   "years": "",
   "client": "Velika planina d.o.o.",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "grad_vzpenjaca",
   "name": "Ljubljana Castle Funicular",
   "name_sl": "Tirna vzpenjača na Ljubljanski grad",
   "evidence": "doc",
   "lat": 46.05014,
   "lon": 14.5097,
   "precision": "surveyed",
   "location": "Ljubljana",
   "sector": "cable",
   "role": "Periodical technical inspections of cableway installations",
   "years": "",
   "client": "Javni zavod Ljubljanski grad",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "kranjskagora_z",
   "name": "Kranjska Gora Cableways",
   "name_sl": "Žičnice Kranjska Gora",
   "evidence": "doc",
   "lat": 46.48537,
   "lon": 13.7871,
   "precision": "settlement",
   "location": "Kranjska Gora",
   "sector": "cable",
   "role": "Periodical technical inspections, and special inspections of sub-systems and safety devices",
   "years": "2013",
   "client": "RTC žičnice Kranjska gora, d.d.",
   "region": "SI042",
   "built": ""
  },
  {
   "id": "vogel",
   "name": "Vogel Cableway",
   "name_sl": "Žičnica Vogel",
   "evidence": "doc",
   "lat": 46.27717,
   "lon": 13.82933,
   "precision": "settlement",
   "location": "Ukanc, Bohinj",
   "sector": "cable",
   "role": "Periodical technical inspections, and special inspections of sub-systems and safety devices",
   "years": "2012",
   "client": "Žičnice Vogel Bohinj, d.d.",
   "region": "SI042",
   "built": ""
  },
  {
   "id": "cerkno_z",
   "name": "Cerkno Cableways",
   "name_sl": "Žičnice Cerkno",
   "evidence": "doc",
   "lat": 46.15026,
   "lon": 14.05896,
   "precision": "settlement",
   "location": "Gorenji Novaki, Cerkno",
   "sector": "cable",
   "role": "Periodical technical inspections, and special inspections of sub-systems and safety devices",
   "years": "2013",
   "client": "Hotel Cerkno d.o.o.",
   "region": "SI043",
   "built": ""
  },
  {
   "id": "golte",
   "name": "Golte Cableway",
   "name_sl": "Žičnica Golte",
   "evidence": "doc",
   "lat": 46.35681,
   "lon": 14.93191,
   "precision": "settlement",
   "location": "Radegunda, Mozirje",
   "sector": "cable",
   "role": "Periodical technical inspections, and special inspections of sub-systems and safety devices",
   "years": "2012–2014",
   "client": "Golte d.o.o.",
   "region": "SI034",
   "built": ""
  },
  {
   "id": "kanin_z",
   "name": "Kanin Cableway",
   "name_sl": "Žičnica Kanin",
   "evidence": "doc",
   "lat": 46.33678,
   "lon": 13.55097,
   "precision": "settlement",
   "location": "Bovec",
   "sector": "cable",
   "role": "Periodical technical inspections, special inspections, and inspection of the support columns",
   "years": "2012",
   "client": "ATC Kanin d.o.o.",
   "region": "SI043",
   "built": ""
  },
  {
   "id": "straza_bled",
   "name": "Straža Bled Cableway",
   "name_sl": "Žičnica Straža Bled",
   "evidence": "doc",
   "lat": 46.3688,
   "lon": 14.11396,
   "precision": "settlement",
   "location": "Bled",
   "sector": "cable",
   "role": "Periodical technical inspections, and special inspections of sub-systems and safety devices",
   "years": "2012",
   "client": "Infrastruktura Bled d.o.o.",
   "region": "SI042",
   "built": ""
  },
  {
   "id": "planica_z",
   "name": "Planica Cableway",
   "name_sl": "Žičnica Planica",
   "evidence": "doc",
   "lat": 46.4965,
   "lon": 13.71314,
   "precision": "settlement",
   "location": "Rateče, Kranjska Gora",
   "sector": "cable",
   "role": "Periodical technical inspections of cableway installations",
   "years": "",
   "client": "Zavod za šport RS Planica",
   "region": "SI042",
   "built": ""
  },
  {
   "id": "ratece_cable",
   "name": "Rateče Cableway Installations",
   "name_sl": "Žičniške naprave Rateče",
   "evidence": "doc",
   "lat": 46.4965,
   "lon": 13.71314,
   "precision": "settlement",
   "location": "Rateče, Kranjska Gora",
   "sector": "cable",
   "role": "Special inspections of sub-systems and safety devices",
   "years": "2012",
   "client": "Smuk d.o.o.",
   "region": "SI042",
   "built": ""
  },
  {
   "id": "rtp_gorica",
   "name": "RTP Gorica Substation",
   "name_sl": "RTP 110/20/10 kV Gorica",
   "evidence": "doc",
   "lat": 45.95914,
   "lon": 13.66857,
   "precision": "settlement",
   "location": "Kromberk, Nova Gorica",
   "sector": "build",
   "role": "Inspection of the quality of the steel structures of the TR-1 substation",
   "years": "2006, 2012",
   "client": "ELEKTRO PRIMORSKA d.d.",
   "region": "SI043",
   "built": ""
  },
  {
   "id": "pecna_reber",
   "name": "Pečna Reber Broadcasting Tower",
   "name_sl": "Oddajni stolp Pečna reber",
   "evidence": "doc",
   "lat": 45.77585,
   "lon": 14.21366,
   "precision": "settlement",
   "location": "Postojna",
   "sector": "build",
   "role": "Inspection of the broadcasting tower",
   "years": "2006",
   "client": "Ministry of Defence RS",
   "region": "SI038",
   "built": ""
  },
  {
   "id": "livarna_crnomelj",
   "name": "Livarna Črnomelj Chimney",
   "name_sl": "Jekleni dimnik, Livarna Črnomelj",
   "evidence": "doc",
   "lat": 45.57377,
   "lon": 15.19421,
   "precision": "settlement",
   "location": "Črnomelj",
   "sector": "build",
   "role": "Inspection of the steel chimney at the foundry",
   "years": "2009",
   "client": "Apeling d.o.o.",
   "region": "SI037",
   "built": ""
  },
  {
   "id": "sz_masts",
   "name": "Railway Electrification Masts",
   "name_sl": "Drogovi elektrifikacije SŽ",
   "evidence": "doc",
   "lat": 46.05237,
   "lon": 14.50504,
   "precision": "settlement",
   "location": "Ljubljana",
   "sector": "build",
   "role": "Analysis of masts after the February 2014 ice storm",
   "years": "2014",
   "client": "SŽ-Infrastruktura, d.o.o.",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "ss_kocevje",
   "name": "Kočevje Secondary School",
   "name_sl": "Gimnazija in srednja šola Kočevje",
   "evidence": "doc",
   "lat": 45.64296,
   "lon": 14.85938,
   "precision": "settlement",
   "location": "Kočevje",
   "sector": "fire",
   "role": "Report on the condition of the part of the building exposed to fire",
   "years": "2013",
   "client": "Kočevje High School and Secondary School",
   "region": "SI037",
   "built": ""
  },
  {
   "id": "os_stara_cerkev",
   "name": "Stara Cerkev Elementary School",
   "name_sl": "Osnovna šola Stara Cerkev",
   "evidence": "doc",
   "lat": 45.66948,
   "lon": 14.83993,
   "precision": "settlement",
   "location": "Stara Cerkev, Kočevje",
   "sector": "fire",
   "role": "Report on the condition of the part of the building exposed to fire",
   "years": "2013",
   "client": "Municipality of Kočevje",
   "region": "SI037",
   "built": ""
  },
  {
   "id": "rakuschev_mlin",
   "name": "Rakuschev Mlin",
   "name_sl": "Rakuschev mlin",
   "evidence": "doc",
   "lat": 46.23011,
   "lon": 15.2637,
   "precision": "municipality",
   "location": "Celje",
   "sector": "fire",
   "role": "Report on the condition of the building after exposure to fire",
   "years": "2014",
   "client": "Adriatic Slovenica d.d.",
   "region": "SI034",
   "built": ""
  },
  {
   "id": "p2b3_sencur",
   "name": "P2B3 Commercial Building",
   "name_sl": "Poslovni objekt P2B3",
   "evidence": "doc",
   "lat": 46.24378,
   "lon": 14.42295,
   "precision": "settlement",
   "location": "Šenčur",
   "sector": "fire",
   "role": "Report on the condition of the building after exposure to fire",
   "years": "2014",
   "client": "Zavarovalnica Triglav d.d.",
   "region": "SI042",
   "built": ""
  },
  {
   "id": "fibran_sodrazica",
   "name": "Fibran Nord Sodražica",
   "name_sl": "Fibran Nord Sodražica",
   "evidence": "doc",
   "lat": 45.76161,
   "lon": 14.63629,
   "precision": "settlement",
   "location": "Sodražica",
   "sector": "fire",
   "role": "Report on the condition of the production hall after exposure to fire",
   "years": "2013",
   "client": "Fibran Nord d.o.o.",
   "region": "SI037",
   "built": ""
  },
  {
   "id": "bovec_quake",
   "name": "Bovec Earthquake Response",
   "name_sl": "Potres v Bovcu",
   "evidence": "doc",
   "lat": 46.33678,
   "lon": 13.55097,
   "precision": "settlement",
   "location": "Bovec",
   "sector": "quake",
   "role": "Effect of the 12 April 1998 earthquake on buildings, people and the environment",
   "years": "1998–2000",
   "client": "Ministry of Science and others",
   "region": "SI043",
   "built": ""
  },
  {
   "id": "soca_quake",
   "name": "Upper Soča Valley Earthquake Repairs",
   "name_sl": "Obnova po potresu v Zgornjem Posočju",
   "evidence": "doc",
   "lat": 46.24643,
   "lon": 13.57799,
   "precision": "settlement",
   "location": "Kobarid",
   "sector": "quake",
   "role": "Damage analysis, design review and third party surveillance of repair and strengthening",
   "years": "2004 onwards",
   "client": "Ministry of the Environment and Spatial Planning",
   "region": "SI043",
   "built": ""
  },
  {
   "id": "lj_seismic",
   "name": "Ljubljana Seismic Risk",
   "name_sl": "Potresno tveganje v Ljubljani",
   "evidence": "doc",
   "lat": 46.05237,
   "lon": 14.50504,
   "precision": "settlement",
   "location": "Ljubljana",
   "sector": "quake",
   "role": "Seismic risk to buildings in the Municipality of Ljubljana",
   "years": "2000–2012",
   "client": "Municipality of Ljubljana",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "idrija_cherplan",
   "name": "Idrija Seismic Risk, CHERPLAN",
   "name_sl": "Potresno tveganje v Idriji, CHERPLAN",
   "evidence": "doc",
   "lat": 46.00131,
   "lon": 14.0221,
   "precision": "settlement",
   "location": "Idrija",
   "sector": "quake",
   "role": "Assessment of the seismic risk to buildings, within the CHERPLAN project",
   "years": "2013",
   "client": "Municipality of Idrija",
   "region": "SI043",
   "built": ""
  },
  {
   "id": "grosuplje_most",
   "name": "Grosuplje Bridge",
   "name_sl": "Most v Grosupljem",
   "evidence": "doc",
   "lat": 45.95512,
   "lon": 14.6562,
   "precision": "settlement",
   "location": "Grosuplje",
   "sector": "bridge",
   "role": "Analysis of the safety of the bridge for traffic loadings",
   "years": "2012",
   "client": "Municipality of Grosuplje",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "catez_bridge",
   "name": "Čatež Bridge over the Sava",
   "name_sl": "Most čez Savo pri Čatežu",
   "evidence": "doc",
   "lat": 45.8926,
   "lon": 15.59788,
   "precision": "settlement",
   "location": "Čatež ob Savi, Brežice",
   "sector": "bridge",
   "role": "Combined earthquake and flood vulnerability assessment",
   "years": "2022–2025",
   "client": "",
   "region": "SI036",
   "built": ""
  },
  {
   "id": "kamnik_bridges",
   "name": "Kamnik Municipal Bridges",
   "name_sl": "Mostovi v Občini Kamnik",
   "evidence": "doc",
   "lat": 46.22608,
   "lon": 14.61083,
   "precision": "settlement",
   "location": "Kamnik",
   "sector": "bridge",
   "role": "Assessment of the level of damage to bridges in the municipality",
   "years": "2015",
   "client": "Municipality of Kamnik",
   "region": "SI041",
   "built": ""
  },
  {
   "id": "maribor_pilots",
   "name": "Maribor Circular Economy Pilot Sites",
   "name_sl": "Pilotne lokacije krožnega gospodarstva, Maribor",
   "evidence": "doc",
   "lat": 46.56247,
   "lon": 15.64398,
   "precision": "settlement",
   "location": "Maribor",
   "sector": "mat",
   "role": "Demonstration of secondary raw materials in urban construction and urban soil",
   "years": "2017–2022",
   "client": "City of Maribor",
   "region": "SI032",
   "built": ""
  },
  {
   "id": "sij_acroni_pavers",
   "name": "Geopolymer Paving at SIJ Acroni",
   "name_sl": "Geopolimerni tlakovci, SIJ Acroni",
   "evidence": "doc",
   "lat": 46.43657,
   "lon": 14.06017,
   "precision": "settlement",
   "location": "Jesenice",
   "sector": "mat",
   "role": "Demonstration of alkali activated paving blocks, GEORIS project",
   "years": "2024",
   "client": "SIJ Acroni",
   "region": "SI042",
   "built": "2024"
  }
 ]
};
